# Generated by Django 5.2 on 2025-06-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrifty', '0006_remove_category_image_categoryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('num_purchases', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
