# Generated by Django 5.2.1 on 2025-06-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrifty', '0009_remove_product_view_count_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
