# Generated by Django 5.2.3 on 2025-07-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrifty', '0020_alter_review_content_type_alter_review_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
